insert into user_demo (username,password) values ( 'admin','admin' );

INSERT INTO currency (name,code,symbol) VALUES ('United Arab Emirates dirham','AED','د.إ');
INSERT INTO currency (name,code,symbol) VALUES ('Afghan afghani','AFN','؋');
INSERT INTO currency (name,code,symbol) VALUES ('Albanian lek','ALL','L');
INSERT INTO currency (name,code,symbol) VALUES ('Armenian dram','AMD','֏');
INSERT INTO currency (name,code,symbol) VALUES ('Argentine peso','ARS','$');
INSERT INTO currency (name,code,symbol) VALUES ('Australian dollar','AUD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Aruban florin','AWG','ƒ');
INSERT INTO currency (name,code,symbol) VALUES ('Azerbaijani manat','AZN','₼');
INSERT INTO currency (name,code,symbol) VALUES ('Barbadian dollar','BBD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Bangladeshi taka','BDT','৳');
INSERT INTO currency (name,code,symbol) VALUES ('Bulgarian lev','BGN','лв.');
INSERT INTO currency (name,code,symbol) VALUES ('Burundian franc','BIF','Fr');
INSERT INTO currency (name,code,symbol) VALUES ('Bermudian dollar','BMD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Brunei dollar','BND','$');
INSERT INTO currency (name,code,symbol) VALUES ('Bolivian boliviano','BOB','Bs.');
INSERT INTO currency (name,code,symbol) VALUES ('Brazilian real','BRL','R$');
INSERT INTO currency (name,code,symbol) VALUES ('Bahamian dollar','BSD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Bhutanese ngultrum','BTN','Nu.');
INSERT INTO currency (name,code,symbol) VALUES ('Botswana pula','BWP','P');
INSERT INTO currency (name,code,symbol) VALUES ('Belarusian ruble','BYN','Br');
INSERT INTO currency (name,code,symbol) VALUES ('Belize dollar','BZD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Canadian dollar','CAD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Congolese franc','CDF','Fr');
INSERT INTO currency (name,code,symbol) VALUES ('Swiss franc','CHF','Fr.');
INSERT INTO currency (name,code,symbol) VALUES ('Chilean peso','CLP','$');
INSERT INTO currency (name,code,symbol) VALUES ('Chinese yuan','CNY','¥ or 元');
INSERT INTO currency (name,code,symbol) VALUES ('Colombian peso','COP','$');
INSERT INTO currency (name,code,symbol) VALUES ('Costa Rican colón','CRC','₡');
INSERT INTO currency (name,code,symbol) VALUES ('Cuban peso','CUP','$');
INSERT INTO currency (name,code,symbol) VALUES ('Cape Verdean escudo','CVE','Esc or $');
INSERT INTO currency (name,code,symbol) VALUES ('Czech koruna','CZK','Kč');
INSERT INTO currency (name,code,symbol) VALUES ('Djiboutian franc','DJF','Fr');
INSERT INTO currency (name,code,symbol) VALUES ('Danish krone','DKK','kr');
INSERT INTO currency (name,code,symbol) VALUES ('Dominican peso','DOP','RD$');
INSERT INTO currency (name,code,symbol) VALUES ('Algerian dinar','DZD','د.ج');
INSERT INTO currency (name,code,symbol) VALUES ('Egyptian pound','EGP','£ or ج.م');
INSERT INTO currency (name,code,symbol) VALUES ('Eritrean nakfa','ERN','Nfk');
INSERT INTO currency (name,code,symbol) VALUES ('Ethiopian birr','ETB','Br');
INSERT INTO currency (name,code,symbol) VALUES ('Euro','EUR','€');
INSERT INTO currency (name,code,symbol) VALUES ('Fijian dollar','FJD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Falkland Islands pound','FKP','£');
INSERT INTO currency (name,code,symbol) VALUES ('Georgian lari','GEL','₾');
INSERT INTO currency (name,code,symbol) VALUES ('Ghanaian cedi','GHS','₵');
INSERT INTO currency (name,code,symbol) VALUES ('Gibraltar pound','GIP','£');
INSERT INTO currency (name,code,symbol) VALUES ('Gambian dalasi','GMD','D');
INSERT INTO currency (name,code,symbol) VALUES ('Guinean franc','GNF','Fr');
INSERT INTO currency (name,code,symbol) VALUES ('Guatemalan quetzal','GTQ','Q');
INSERT INTO currency (name,code,symbol) VALUES ('Guyanese dollar','GYD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Hong Kong dollar','HKD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Honduran lempira','HNL','L');
INSERT INTO currency (name,code,symbol) VALUES ('Croatian kuna','HRK','kn');
INSERT INTO currency (name,code,symbol) VALUES ('Haitian gourde','HTG','G');
INSERT INTO currency (name,code,symbol) VALUES ('Hungarian forint','HUF','Ft');
INSERT INTO currency (name,code,symbol) VALUES ('Indonesian rupiah','IDR','Rp');
INSERT INTO currency (name,code,symbol) VALUES ('Israeli new shekel','ILS','₪');
INSERT INTO currency (name,code,symbol) VALUES ('Indian rupee','INR','₹');
INSERT INTO currency (name,code,symbol) VALUES ('Iraqi dinar','IQD','ع.د');
INSERT INTO currency (name,code,symbol) VALUES ('Iranian rial','IRR','﷼');
INSERT INTO currency (name,code,symbol) VALUES ('Icelandic króna','ISK','kr');
INSERT INTO currency (name,code,symbol) VALUES ('Jamaican dollar','JMD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Jordanian dinar','JOD','د.ا');
INSERT INTO currency (name,code,symbol) VALUES ('Japanese yen','JPY','¥ or 円');
INSERT INTO currency (name,code,symbol) VALUES ('Kenyan shilling','KES','Sh');
INSERT INTO currency (name,code,symbol) VALUES ('Kyrgyzstani som','KGS','с');
INSERT INTO currency (name,code,symbol) VALUES ('Cambodian riel','KHR','៛');
INSERT INTO currency (name,code,symbol) VALUES ('Comorian franc','KMF','Fr');
INSERT INTO currency (name,code,symbol) VALUES ('North Korean won','KPW','₩');
INSERT INTO currency (name,code,symbol) VALUES ('South Korean won','KRW','₩');
INSERT INTO currency (name,code,symbol) VALUES ('Kuwaiti dinar','KWD','د.ك');
INSERT INTO currency (name,code,symbol) VALUES ('Cayman Islands dollar','KYD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Kazakhstani tenge','KZT','₸');
INSERT INTO currency (name,code,symbol) VALUES ('Lao kip','LAK','₭');
INSERT INTO currency (name,code,symbol) VALUES ('Lebanese pound','LBP','ل.ل');
INSERT INTO currency (name,code,symbol) VALUES ('Sri Lankan rupee','LKR','Rs, රු or ரூ');
INSERT INTO currency (name,code,symbol) VALUES ('Liberian dollar','LRD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Lesotho loti','LSL','L');
INSERT INTO currency (name,code,symbol) VALUES ('Libyan dinar','LYD','ل.د');
INSERT INTO currency (name,code,symbol) VALUES ('Moroccan dirham','MAD','د.م.');
INSERT INTO currency (name,code,symbol) VALUES ('Moldovan leu','MDL','L');
INSERT INTO currency (name,code,symbol) VALUES ('Malagasy ariary','MGA','Ar');
INSERT INTO currency (name,code,symbol) VALUES ('Macedonian denar','MKD','ден');
INSERT INTO currency (name,code,symbol) VALUES ('Burmese kyat','MMK','Ks');
INSERT INTO currency (name,code,symbol) VALUES ('Mongolian tögrög','MNT','₮');
INSERT INTO currency (name,code,symbol) VALUES ('Macanese pataca','MOP','MOP$');
INSERT INTO currency (name,code,symbol) VALUES ('Mauritanian ouguiya','MRU','UM');
INSERT INTO currency (name,code,symbol) VALUES ('Mauritian rupee','MUR','₨');
INSERT INTO currency (name,code,symbol) VALUES ('Maldivian rufiyaa','MVR','.ރ');
INSERT INTO currency (name,code,symbol) VALUES ('Malawian kwacha','MWK','MK');
INSERT INTO currency (name,code,symbol) VALUES ('Mexican peso','MXN','$');
INSERT INTO currency (name,code,symbol) VALUES ('Malaysian ringgit','MYR','RM');
INSERT INTO currency (name,code,symbol) VALUES ('Mozambican metical','MZN','MT');
INSERT INTO currency (name,code,symbol) VALUES ('Namibian dollar','NAD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Nigerian naira','NGN','₦');
INSERT INTO currency (name,code,symbol) VALUES ('Nicaraguan córdoba','NIO','C$');
INSERT INTO currency (name,code,symbol) VALUES ('Norwegian krone','NOK','kr');
INSERT INTO currency (name,code,symbol) VALUES ('Nepalese rupee','NPR','रू');
INSERT INTO currency (name,code,symbol) VALUES ('New Zealand dollar','NZD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Omani rial','OMR','ر.ع.');
INSERT INTO currency (name,code,symbol) VALUES ('Panamanian balboa','PAB','B/.');
INSERT INTO currency (name,code,symbol) VALUES ('Peruvian sol','PEN','S/.');
INSERT INTO currency (name,code,symbol) VALUES ('Papua New Guinean kina','PGK','K');
INSERT INTO currency (name,code,symbol) VALUES ('Philippine peso','PHP','₱');
INSERT INTO currency (name,code,symbol) VALUES ('Pakistani rupee','PKR','₨');
INSERT INTO currency (name,code,symbol) VALUES ('Polish złoty','PLN','zł');
INSERT INTO currency (name,code,symbol) VALUES ('Paraguayan guaraní','PYG','₲');
INSERT INTO currency (name,code,symbol) VALUES ('Qatari riyal','QAR','ر.ق');
INSERT INTO currency (name,code,symbol) VALUES ('Romanian leu','RON','lei');
INSERT INTO currency (name,code,symbol) VALUES ('Serbian dinar','RSD','дин. or din.');
INSERT INTO currency (name,code,symbol) VALUES ('Russian ruble','RUB','₽');
INSERT INTO currency (name,code,symbol) VALUES ('Rwandan franc','RWF','Fr');
INSERT INTO currency (name,code,symbol) VALUES ('Saudi riyal','SAR','﷼');
INSERT INTO currency (name,code,symbol) VALUES ('Solomon Islands dollar','SBD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Sudanese pound','SDG','ج.س.');
INSERT INTO currency (name,code,symbol) VALUES ('Swedish krona','SEK','kr');
INSERT INTO currency (name,code,symbol) VALUES ('Singapore dollar','SGD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Saint Helena pound','SHP','£');
INSERT INTO currency (name,code,symbol) VALUES ('Sierra Leonean leone','SLL','Le');
INSERT INTO currency (name,code,symbol) VALUES ('Somali shilling','SOS','Sh');
INSERT INTO currency (name,code,symbol) VALUES ('Surinamese dollar','SRD','$');
INSERT INTO currency (name,code,symbol) VALUES ('South Sudanese pound','SSP','£');
INSERT INTO currency (name,code,symbol) VALUES ('São Tomé and Príncipe dobra','STN','Db');
INSERT INTO currency (name,code,symbol) VALUES ('Syrian pound','SYP','£ or ل.س');
INSERT INTO currency (name,code,symbol) VALUES ('Swazi lilangeni','SZL','L');
INSERT INTO currency (name,code,symbol) VALUES ('Thai baht','THB','฿');
INSERT INTO currency (name,code,symbol) VALUES ('Tajikistani somoni','TJS','ЅМ');
INSERT INTO currency (name,code,symbol) VALUES ('Turkmenistan manat','TMT','m');
INSERT INTO currency (name,code,symbol) VALUES ('Tunisian dinar','TND','د.ت');
INSERT INTO currency (name,code,symbol) VALUES ('Turkish lira','TRY','₺');
INSERT INTO currency (name,code,symbol) VALUES ('Trinidad and Tobago dollar','TTD','$');
INSERT INTO currency (name,code,symbol) VALUES ('New Taiwan dollar','TWD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Tanzanian shilling','TZS','Sh');
INSERT INTO currency (name,code,symbol) VALUES ('United States dollar','USD','$');
INSERT INTO currency (name,code,symbol) VALUES ('Uruguayan peso','UYU','$');
INSERT INTO currency (name,code,symbol) VALUES ('Venezuelan bolívar soberano','VES','Bs.S. or Bs.');
INSERT INTO currency (name,code,symbol) VALUES ('Vietnamese đồng','VND','₫');
INSERT INTO currency (name,code,symbol) VALUES ('Samoan tālā','WST','T');
INSERT INTO currency (name,code,symbol) VALUES ('Central African CFA franc','XAF','Fr');
INSERT INTO currency (name,code,symbol) VALUES ('Eastern Caribbean dollar','XCD','$');
INSERT INTO currency (name,code,symbol) VALUES ('West African CFA franc','XOF','Fr');
INSERT INTO currency (name,code,symbol) VALUES ('Ugandan shilling','UGX','Sh');
INSERT INTO currency (name,code,symbol) VALUES ('CFP franc','XPF','₣');
INSERT INTO currency (name,code,symbol) VALUES ('Yemeni rial','YER','﷼');
INSERT INTO currency (name,code,symbol) VALUES ('South African rand','ZAR','R');

-- INSERT INTO exchange_history (from,to,amount,rate,amountConvert,status) VALUES ( 'test','test',0,0,0,0 );